import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-stone-800">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            CookNet
          </h1>
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
            <h3 className="text-2xl font-bold text-white">LANDING PAGE! →</h3>
            <Link href={"/sign-up"}>
              <span className="text-2xl font-bold text-white">SIGN UP</span>
            </Link>

            <div className="text-lg text-white">
              This is the social media med app!!!
            </div>
          </div>
          <p className="text-2xl text-white"></p>
        </div>
      </main>
    </>
  );
};

export default Home;
